// Contract addresses (auto-generated by deploy.sh)
export const ESCROW_ADDRESS = "0x5FbDB2315678afecb367f032d93F642f64180aa3";
export const TOKEN_A_ADDRESS = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512";
export const TOKEN_B_ADDRESS = "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0";

// Import ABIs
import EscrowABI from './abis/Escrow.json';
import ERC20ABI from './abis/ERC20.json';

export { EscrowABI, ERC20ABI };

// Test accounts
export const TEST_ACCOUNTS = {
  account0: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
  account1: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
  account2: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
};
