#!/bin/bash

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}   Escrow DApp Deployment Script${NC}"
echo -e "${BLUE}========================================${NC}\n"

# Check if Anvil is running
if ! curl -s http://localhost:8545 > /dev/null 2>&1; then
    echo -e "${RED}Error: Anvil is not running!${NC}"
    echo "Please start Anvil first with: anvil"
    exit 1
fi

echo -e "${GREEN}✓ Anvil is running${NC}\n"

# Set environment variables for deployment
export PRIVATE_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"  # Anvil account #0

# Navigate to smart contracts directory
cd sc

echo -e "${BLUE}Building contracts...${NC}"
forge build

if [ $? -ne 0 ]; then
    echo -e "${RED}Error: Contract compilation failed!${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Contracts compiled successfully${NC}\n"

echo -e "${BLUE}Deploying contracts to local network...${NC}"
DEPLOY_OUTPUT=$(forge script script/Deploy.s.sol:DeployScript \
    --rpc-url http://localhost:8545 \
    --broadcast \
    --legacy 2>&1)

if [ $? -ne 0 ]; then
    echo -e "${RED}Error: Deployment failed!${NC}"
    echo "$DEPLOY_OUTPUT"
    exit 1
fi

echo -e "${GREEN}✓ Contracts deployed successfully${NC}\n"

# Extract addresses from forge output
ESCROW_ADDRESS=$(echo "$DEPLOY_OUTPUT" | grep "ESCROW_ADDRESS=" | sed 's/.*ESCROW_ADDRESS= //' | tr -d '\n\r')
TOKEN_A_ADDRESS=$(echo "$DEPLOY_OUTPUT" | grep "TOKEN_A_ADDRESS=" | sed 's/.*TOKEN_A_ADDRESS= //' | tr -d '\n\r')
TOKEN_B_ADDRESS=$(echo "$DEPLOY_OUTPUT" | grep "TOKEN_B_ADDRESS=" | sed 's/.*TOKEN_B_ADDRESS= //' | tr -d '\n\r')

# Save to deployment-info.txt in parent directory
cat > ../deployment-info.txt << EOF
ESCROW_ADDRESS=$ESCROW_ADDRESS
TOKEN_A_ADDRESS=$TOKEN_A_ADDRESS
TOKEN_B_ADDRESS=$TOKEN_B_ADDRESS
EOF

if [ ! -z "$ESCROW_ADDRESS" ]; then

    echo -e "${BLUE}Deployment Addresses:${NC}"
    echo -e "Escrow:  ${GREEN}$ESCROW_ADDRESS${NC}"
    echo -e "Token A: ${GREEN}$TOKEN_A_ADDRESS${NC}"
    echo -e "Token B: ${GREEN}$TOKEN_B_ADDRESS${NC}\n"

    # Extract ABIs
    echo -e "${BLUE}Extracting ABIs...${NC}"
    mkdir -p ../web/lib/abis

    # Extract Escrow ABI
    cat out/Escrow.sol/Escrow.json | jq '.abi' > ../web/lib/abis/Escrow.json

    # Extract ERC20 ABI from MockToken
    cat out/MockToken.sol/MockToken.json | jq '.abi' > ../web/lib/abis/ERC20.json

    echo -e "${GREEN}✓ ABIs extracted to web/lib/abis/${NC}\n"

    # Update contracts.ts with addresses
    echo -e "${BLUE}Updating web/lib/contracts.ts...${NC}"

    cat > ../web/lib/contracts.ts << EOF
// Contract addresses (auto-generated by deploy.sh)
export const ESCROW_ADDRESS = "$ESCROW_ADDRESS";
export const TOKEN_A_ADDRESS = "$TOKEN_A_ADDRESS";
export const TOKEN_B_ADDRESS = "$TOKEN_B_ADDRESS";

// Import ABIs
import EscrowABI from './abis/Escrow.json';
import ERC20ABI from './abis/ERC20.json';

export { EscrowABI, ERC20ABI };

// Test accounts
export const TEST_ACCOUNTS = {
  account0: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
  account1: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
  account2: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
};
EOF

    echo -e "${GREEN}✓ contracts.ts updated${NC}\n"

else
    echo -e "${RED}Error: Failed to extract deployment addresses!${NC}"
    exit 1
fi

cd ..

echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}   Deployment Complete!${NC}"
echo -e "${BLUE}========================================${NC}\n"

echo -e "Next steps:"
echo -e "1. Start the frontend: ${BLUE}cd web && npm run dev${NC}"
echo -e "2. Open http://localhost:3000 in your browser"
echo -e "3. Connect MetaMask using one of the test accounts\n"

echo -e "Test Account #0 (Owner):"
echo -e "Address: ${GREEN}0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266${NC}"
echo -e "Private Key: ${GREEN}0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80${NC}\n"

echo -e "Test Account #1:"
echo -e "Address: ${GREEN}0x70997970C51812dc3A010C7d01b50e0d17dc79C8${NC}"
echo -e "Private Key: ${GREEN}0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d${NC}\n"

echo -e "Test Account #2:"
echo -e "Address: ${GREEN}0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC${NC}"
echo -e "Private Key: ${GREEN}0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a${NC}\n"
